[package]
name = "render-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.31.0"
rand = "0.8.5"
egui_node_graph = "0.3.0"
egui = "0.18.1"
eframe = "0.18.0"
egui_glium = "0.18.0"
ouroboros = "0.15.0"
itertools = "0.10.2"
isf = "0.1.0"
gl = "0.14.0"

spout_rust = { path = "./spout" }
tri-mesh = "0.5.0"
glam = "0.21.3"

strum_macros = "0.24"
strum = { version = "0.24", features = ["derive"] }

slotmap = "1.0.6"
native-dialog = "0.6.3"
enum_dispatch = "0.3.8"
thiserror = "1.0.37"
wavefront_obj = "10.0.0"
glsl = "6.0.1"
naga = { version="0.10.0", features=["glsl-in"] }

# clap = { version = "3.2.8", features = ["derive"] }
# tracing = "0.1.35"
# tracing-subscriber = "0.3"
# palette = "0.6.0"
# nannou_osc = "0.18.0"
# pprof = { version = "0.10", features = ["flamegraph"] }
# circular-queue = "0.2.6"