[package]
name = "glium_rpi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
rand = "0.8"
stars = { path = "../stars" }
glam = "0.17.3"
nannou_osc = "0.18.0"