[package]
name = "ffgl-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "render_graph_lib"
crate-type = ["cdylib"]
panic = "unwind"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
